#!/bin/bash

# Demo script để test Remote Mail Client
echo "=== Remote Mail Client Demo ==="
echo ""
echo "1. Đảm bảo server game đang chạy"
echo "2. Đảm bảo có tài khoản admin trong database"
echo "3. Chạy Remote Mail Client:"
echo ""
echo "  c"
echo ""
echo "4. Nhập thông tin kết nối:"
echo "   - Server IP: localhost (hoặc IP server)"
echo "   - Port: 14446"
echo "   - Username: admin"
echo "   - Password: [mật khẩu admin]"
echo ""
echo "5. Sau khi kết nối thành công, bạn có thể:"
echo "   - Gửi thư cho người chơi"
echo "   - Thêm vật phẩm vào thư"
echo "   - Thêm options cho vật phẩm"
echo ""
echo "Lưu ý: Remote Mail Server sẽ tự động chạy khi khởi động server game"
echo "       trên port 14446 (khác với game server port 14445)"
